site_name: OpenML Documentation
repo_url: https://github.com/openml/docs/
site_url: https://docs.openml.org/
edit_uri: edit/master/docs/
theme:
  name: "material"
  language: "en"
  palette:
    primary: indigo
    accent: indigo
  font:
    text: "Roboto"
    code: "Roboto Mono"
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - content.action.edit
  plugins:
    - search:
      separator: '[\s\-\.]+'
      lang:
        - en
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - toc:
      permalink: true
nav:
  - Bootcamp:
      - Get started: index.md
      - Integrations:
          - "scikit-learn": sklearn.md
          - "mlr": mlr.md
          - "WEKA": Weka.md
          - "MOA": MOA.md
      - Benchmarking: benchmark.md
      - Governance: Governance.md
      - Terms: terms.md
  - Contributors:
      - "How to Contribute": Contributing.md
      - "Documenting": OpenML-Docs.md
      - "Website":
          - "Getting started": Website.md
          - "Flask backend": Flask.md
          - "React frontend": React.md
          - "Dash visualizations": Dash.md
      - "Backend":
          - "Local Installation": Local-Installation.md
          - "API Development": API-development.md
          - "Evaluation Engine": Java-App.md
      - "OpenML Definition": OpenML_definition.md
      - "Client Development": Client-API-Standards.md
      - "Datasets": Datasets.md
      - "Resources": resources.md
plugins:
    - redirects:
        redirect_maps:
            'APIs.md': 'https://www.openml.org/apis'
            'REST-API.md': 'https://www.openml.org/apis'
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
